trigger:
  branches:
    include:
      - main

variables:
  # Variables de entorno
  ACR_NAME: "SumativaTres" # Colocar el nombre de tu ACR
  IMAGE_NAME: "dockermysql" # Colocar el Nombre de Imagen
  SERVICE_CONNECTION_NAME: "sumativaTresDockerRegistry" # Colocar nombre del Service Connection ubicado en Docker Registry-- Azure Container Registry

jobs:
  - job: BuildAndPush
    pool:
      name: 'default'  # Usa el agente autohospedado
    steps:
      - task: Docker@2
        inputs:
          command: "buildAndPush"
          containerRegistry: "$(SERVICE_CONNECTION_NAME)"
          repository: "$(ACR_NAME).azurecr.io/$(IMAGE_NAME)"
          dockerfile: "**/Dockerfile"
          tags: |
            latest
        displayName: "Build and Push Docker Image ACR"
